### ISSUE TITLE
Error: Protocol "https:" not supported. Expected "http:".

### ISSUE THREAD

**Issue by neilstuartcraig** [substack/https-browserify#5]
Hi 

I have hit a problem with this package in that when I use it server-side (my code will run on client and on server), i see an error on making a GET:

```shell
Error: Protocol "https:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:56:11)
    at Object.exports.request (http.js:31:10)
    at Object.https.request (/path/to/proj/node_modules/https-browserify/index.js:13:25)
    at requestAPIData (/path/to/proj/src/jsx/APIRequest.js:73:14)
    at indexSrvFn (/path/to/proj/server.js:60:7)
    at Layer.handle [as handle_request] (/path/to/proj/node_modules/express/lib/router/layer.js:95:5)
    at next (/path/to/proj/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/path/to/proj/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/path/to/proj/node_modules/express/lib/router/layer.js:95:5)
    at /path/to/proj/node_modules/express/lib/router/index.js:277:22
```

When I look in this package's `index.js`, i see:

```js
var http = require('http');
```

Which makes sense versus the error above. Changing the above to:

```js
var http = require('https');
```

Solves the problem.

Is this package intended to work server-side or not? It seems to with the above change but will that break client-side operation? 

Cheers

**Comment by feross** [comment]
No, this is for client side only. I would just use:

var https = require('https')

On both the client and the server. Browserify takes care of using a
client-side shim for you. :)

**Comment by neilstuartcraig** [comment]
OK, thanks @feross - i'm surprised (probably due to my lack of knowledge of this pkg) that it's based off/extennded from `http` rather than `https` but i'm sure there must be a reason.

Thanks for the advice, i'll progress with `https` for the moment, just trying to track down a strange browserify error which i have traced to my file which makes HTTPS requests.

Cheers

**Comment by jasDestiny** [comment]
I have required https protocol and not http in one of my projects, still the same problem persists. Any ideas?
